

while _G.amogus do
getgenv().WalkSpeedValue = 50; --set your desired walkspeed here
local Player = game:service'Players'.LocalPlayer;
Player.Character.Humanoid:GetPropertyChangedSignal'WalkSpeed':Connect(function()
Player.Character.Humanoid.WalkSpeed = getgenv().WalkSpeedValue;
end)
Player.Character.Humanoid.WalkSpeed = getgenv().WalkSpeedValue;
--end
game.Lighting.TimeOfDay = "00:00:00:"
wait(0)
game.Lighting.TimeOfDay = "01:00:00:"
wait(0)
game.Lighting.TimeOfDay = "02:00:00:"
wait(0)
game.Lighting.TimeOfDay = "03:00:00:"
wait(0)
game.Lighting.TimeOfDay = "04:00:00:"
wait(0)
game.Lighting.TimeOfDay = "05:00:00:"
wait(0)
game.Lighting.TimeOfDay = "06:00:00:"
wait(0)
game.Lighting.TimeOfDay = "07:00:00:"
wait(0)
game.Lighting.TimeOfDay = "08:00:00:"
wait(0)
game.Lighting.TimeOfDay = "09:00:00:"
wait(0.8)
game.Lighting.TimeOfDay = "10:00:00:"
wait(0.5)
game.Lighting.TimeOfDay = "11:00:00:"
wait(0)
game.Lighting.TimeOfDay = "12:00:00:"
wait(0)
game.Lighting.TimeOfDay = "13:00:00:"
wait(0)
game.Lighting.TimeOfDay = "14:00:00:"
wait(0)
game.Lighting.TimeOfDay = "15:00:00:"
wait(0)
game.Lighting.TimeOfDay = "16:00:00:"
wait(0)
game.Lighting.TimeOfDay = "17:00:00:"
wait(0)
game.Lighting.TimeOfDay = "18:00:00:"
wait(0)
game.Lighting.TimeOfDay = "19:00:00:"
wait(0)
game.Lighting.TimeOfDay = "20:00:00:"
wait(0)
game.Lighting.TimeOfDay = "21:00:00:"
wait(0)
game.Lighting.TimeOfDay = "22:00:00:"
wait(0)
game.Lighting.TimeOfDay = "23:00:00:"
wait(0)
game.Lighting.TimeOfDay = "24:00:00:"

wait(2)

getgenv().WalkSpeedValue = 100; --set your desired walkspeed here
local Player = game:service'Players'.LocalPlayer;
Player.Character.Humanoid:GetPropertyChangedSignal'WalkSpeed':Connect(function()
Player.Character.Humanoid.WalkSpeed = getgenv().WalkSpeedValue;
end)
Player.Character.Humanoid.WalkSpeed = getgenv().WalkSpeedValue;
--end
game.Lighting.TimeOfDay = "00:00:00:"
wait(0)
game.Lighting.TimeOfDay = "01:00:00:"
wait(0)
game.Lighting.TimeOfDay = "02:00:00:"
wait(0)
game.Lighting.TimeOfDay = "03:00:00:"
wait(0)
game.Lighting.TimeOfDay = "04:00:00:"
wait(0)
game.Lighting.TimeOfDay = "05:00:00:"
wait(0)
game.Lighting.TimeOfDay = "06:00:00:"
wait(0)
game.Lighting.TimeOfDay = "07:00:00:"
wait(0)
game.Lighting.TimeOfDay = "08:00:00:"
wait(0)
game.Lighting.TimeOfDay = "09:00:00:"
wait(0.8)
game.Lighting.TimeOfDay = "10:00:00:"
wait(0.5)
game.Lighting.TimeOfDay = "11:00:00:"
wait(0)
game.Lighting.TimeOfDay = "12:00:00:"
wait(0)
game.Lighting.TimeOfDay = "13:00:00:"
wait(0)
game.Lighting.TimeOfDay = "14:00:00:"
wait(0)
game.Lighting.TimeOfDay = "15:00:00:"
wait(0)
game.Lighting.TimeOfDay = "16:00:00:"
wait(0)
game.Lighting.TimeOfDay = "17:00:00:"
wait(0)
game.Lighting.TimeOfDay = "18:00:00:"
wait(0)
game.Lighting.TimeOfDay = "19:00:00:"
wait(0)
game.Lighting.TimeOfDay = "20:00:00:"
wait(0)
game.Lighting.TimeOfDay = "21:00:00:"
wait(0)
game.Lighting.TimeOfDay = "22:00:00:"
wait(0)
game.Lighting.TimeOfDay = "23:00:00:"
wait(0)
game.Lighting.TimeOfDay = "24:00:00:"
wait(2)
getgenv().WalkSpeedValue = 150; --set your desired walkspeed here
local Player = game:service'Players'.LocalPlayer;
Player.Character.Humanoid:GetPropertyChangedSignal'WalkSpeed':Connect(function()
Player.Character.Humanoid.WalkSpeed = getgenv().WalkSpeedValue;
end)
Player.Character.Humanoid.WalkSpeed = getgenv().WalkSpeedValue;
--end
game.Lighting.TimeOfDay = "00:00:00:"
wait(0)
game.Lighting.TimeOfDay = "01:00:00:"
wait(0)
game.Lighting.TimeOfDay = "02:00:00:"
wait(0)
game.Lighting.TimeOfDay = "03:00:00:"
wait(0)
game.Lighting.TimeOfDay = "04:00:00:"
wait(0)
game.Lighting.TimeOfDay = "05:00:00:"
wait(0)
game.Lighting.TimeOfDay = "06:00:00:"
wait(0)
game.Lighting.TimeOfDay = "07:00:00:"
wait(0)
game.Lighting.TimeOfDay = "08:00:00:"
wait(0)
game.Lighting.TimeOfDay = "09:00:00:"
wait(0.8)
game.Lighting.TimeOfDay = "10:00:00:"
wait(0.5)
game.Lighting.TimeOfDay = "11:00:00:"
wait(0)
game.Lighting.TimeOfDay = "12:00:00:"
wait(0)
game.Lighting.TimeOfDay = "13:00:00:"
wait(0)
game.Lighting.TimeOfDay = "14:00:00:"
wait(0)
game.Lighting.TimeOfDay = "15:00:00:"
wait(0)
game.Lighting.TimeOfDay = "16:00:00:"
wait(0)
game.Lighting.TimeOfDay = "17:00:00:"
wait(0)
game.Lighting.TimeOfDay = "18:00:00:"
wait(0)
game.Lighting.TimeOfDay = "19:00:00:"
wait(0)
game.Lighting.TimeOfDay = "20:00:00:"
wait(0)
game.Lighting.TimeOfDay = "21:00:00:"
wait(0)
game.Lighting.TimeOfDay = "22:00:00:"
wait(0)
game.Lighting.TimeOfDay = "23:00:00:"
wait(0)
game.Lighting.TimeOfDay = "24:00:00:"
wait(2)
getgenv().WalkSpeedValue = 200; --set your desired walkspeed here
local Player = game:service'Players'.LocalPlayer;
Player.Character.Humanoid:GetPropertyChangedSignal'WalkSpeed':Connect(function()
Player.Character.Humanoid.WalkSpeed = getgenv().WalkSpeedValue;
end)
Player.Character.Humanoid.WalkSpeed = getgenv().WalkSpeedValue;
--end
game.Lighting.TimeOfDay = "00:00:00:"
wait(0)
game.Lighting.TimeOfDay = "01:00:00:"
wait(0)
game.Lighting.TimeOfDay = "02:00:00:"
wait(0)
game.Lighting.TimeOfDay = "03:00:00:"
wait(0)
game.Lighting.TimeOfDay = "04:00:00:"
wait(0)
game.Lighting.TimeOfDay = "05:00:00:"
wait(0)
game.Lighting.TimeOfDay = "06:00:00:"
wait(0)
game.Lighting.TimeOfDay = "07:00:00:"
wait(0)
game.Lighting.TimeOfDay = "08:00:00:"
wait(0)
game.Lighting.TimeOfDay = "09:00:00:"
wait(0.8)
game.Lighting.TimeOfDay = "10:00:00:"
wait(0.5)
game.Lighting.TimeOfDay = "11:00:00:"
wait(0)
game.Lighting.TimeOfDay = "12:00:00:"
wait(0)
game.Lighting.TimeOfDay = "13:00:00:"
wait(0)
game.Lighting.TimeOfDay = "14:00:00:"
wait(0)
game.Lighting.TimeOfDay = "15:00:00:"
wait(0)
game.Lighting.TimeOfDay = "16:00:00:"
wait(0)
game.Lighting.TimeOfDay = "17:00:00:"
wait(0)
game.Lighting.TimeOfDay = "18:00:00:"
wait(0)
game.Lighting.TimeOfDay = "19:00:00:"
wait(0)
game.Lighting.TimeOfDay = "20:00:00:"
wait(0)
game.Lighting.TimeOfDay = "21:00:00:"
wait(0)
game.Lighting.TimeOfDay = "22:00:00:"
wait(0)
game.Lighting.TimeOfDay = "23:00:00:"
wait(0)
game.Lighting.TimeOfDay = "24:00:00:"
wait(2)
getgenv().WalkSpeedValue = 150; --set your desired walkspeed here
local Player = game:service'Players'.LocalPlayer;
Player.Character.Humanoid:GetPropertyChangedSignal'WalkSpeed':Connect(function()
Player.Character.Humanoid.WalkSpeed = getgenv().WalkSpeedValue;
end)
Player.Character.Humanoid.WalkSpeed = getgenv().WalkSpeedValue;
--end
game.Lighting.TimeOfDay = "00:00:00:"
wait(0)
game.Lighting.TimeOfDay = "01:00:00:"
wait(0)
game.Lighting.TimeOfDay = "02:00:00:"
wait(0)
game.Lighting.TimeOfDay = "03:00:00:"
wait(0)
game.Lighting.TimeOfDay = "04:00:00:"
wait(0)
game.Lighting.TimeOfDay = "05:00:00:"
wait(0)
game.Lighting.TimeOfDay = "06:00:00:"
wait(0)
game.Lighting.TimeOfDay = "07:00:00:"
wait(0)
game.Lighting.TimeOfDay = "08:00:00:"
wait(0)
game.Lighting.TimeOfDay = "09:00:00:"
wait(0)
game.Lighting.TimeOfDay = "10:00:00:"
wait(0)
game.Lighting.TimeOfDay = "11:00:00:"
wait(0)
game.Lighting.TimeOfDay = "12:00:00:"
wait(0)
game.Lighting.TimeOfDay = "13:00:00:"
wait(0)
game.Lighting.TimeOfDay = "14:00:00:"
wait(0)
game.Lighting.TimeOfDay = "15:00:00:"
wait(0)
game.Lighting.TimeOfDay = "16:00:00:"
wait(0)
game.Lighting.TimeOfDay = "17:00:00:"
wait(0)
game.Lighting.TimeOfDay = "18:00:00:"
wait(0)
game.Lighting.TimeOfDay = "19:00:00:"
wait(0)
game.Lighting.TimeOfDay = "20:00:00:"
wait(0)
game.Lighting.TimeOfDay = "21:00:00:"
wait(0)
game.Lighting.TimeOfDay = "22:00:00:"
wait(0)
game.Lighting.TimeOfDay = "23:00:00:"
wait(0)
game.Lighting.TimeOfDay = "24:00:00:"
game.Lighting.TimeOfDay = "00:00:00:"
wait(0)
game.Lighting.TimeOfDay = "01:00:00:"
wait(0)
game.Lighting.TimeOfDay = "02:00:00:"
wait(0)
game.Lighting.TimeOfDay = "03:00:00:"
wait(0)
game.Lighting.TimeOfDay = "04:00:00:"
wait(0)
game.Lighting.TimeOfDay = "05:00:00:"
wait(0)
game.Lighting.TimeOfDay = "06:00:00:"
wait(0)
game.Lighting.TimeOfDay = "07:00:00:"
wait(0)
game.Lighting.TimeOfDay = "08:00:00:"
wait(0)
game.Lighting.TimeOfDay = "09:00:00:"
wait(0)
game.Lighting.TimeOfDay = "10:00:00:"
wait(0)
game.Lighting.TimeOfDay = "11:00:00:"
wait(0)
game.Lighting.TimeOfDay = "12:00:00:"
wait(0)
game.Lighting.TimeOfDay = "13:00:00:"
wait(0)
game.Lighting.TimeOfDay = "14:00:00:"
wait(0)
game.Lighting.TimeOfDay = "15:00:00:"
wait(0)
game.Lighting.TimeOfDay = "16:00:00:"
wait(0)
game.Lighting.TimeOfDay = "17:00:00:"
wait(0)
game.Lighting.TimeOfDay = "18:00:00:"
wait(0)
game.Lighting.TimeOfDay = "19:00:00:"
wait(0)
game.Lighting.TimeOfDay = "20:00:00:"
wait(0)
game.Lighting.TimeOfDay = "21:00:00:"
wait(0)
game.Lighting.TimeOfDay = "22:00:00:"
wait(0)
game.Lighting.TimeOfDay = "23:00:00:"
wait(0)
game.Lighting.TimeOfDay = "24:00:00:"game.Lighting.TimeOfDay = "00:00:00:"
wait(0)
game.Lighting.TimeOfDay = "01:00:00:"
wait(0)
game.Lighting.TimeOfDay = "02:00:00:"
wait(0)
game.Lighting.TimeOfDay = "03:00:00:"
wait(0)
game.Lighting.TimeOfDay = "04:00:00:"
wait(0)
game.Lighting.TimeOfDay = "05:00:00:"
wait(0)
game.Lighting.TimeOfDay = "06:00:00:"
wait(0)
game.Lighting.TimeOfDay = "07:00:00:"
wait(0)
game.Lighting.TimeOfDay = "08:00:00:"
wait(0)
game.Lighting.TimeOfDay = "09:00:00:"
wait(0)
game.Lighting.TimeOfDay = "10:00:00:"
wait(0)
game.Lighting.TimeOfDay = "11:00:00:"
wait(0)
game.Lighting.TimeOfDay = "12:00:00:"
wait(0)
game.Lighting.TimeOfDay = "13:00:00:"
wait(0)
game.Lighting.TimeOfDay = "14:00:00:"
wait(0)
game.Lighting.TimeOfDay = "15:00:00:"
wait(0)
game.Lighting.TimeOfDay = "16:00:00:"
wait(0)
game.Lighting.TimeOfDay = "17:00:00:"
wait(0)
game.Lighting.TimeOfDay = "18:00:00:"
wait(0)
game.Lighting.TimeOfDay = "19:00:00:"
wait(0)
game.Lighting.TimeOfDay = "20:00:00:"
wait(0)
game.Lighting.TimeOfDay = "21:00:00:"
wait(0)
game.Lighting.TimeOfDay = "22:00:00:"
wait(0)
game.Lighting.TimeOfDay = "23:00:00:"
wait(0)
game.Lighting.TimeOfDay = "24:00:00:"game.Lighting.TimeOfDay = "00:00:00:"
wait(0)
game.Lighting.TimeOfDay = "01:00:00:"
wait(0)
game.Lighting.TimeOfDay = "02:00:00:"
wait(0)
game.Lighting.TimeOfDay = "03:00:00:"
wait(0)
game.Lighting.TimeOfDay = "04:00:00:"
wait(0)
game.Lighting.TimeOfDay = "05:00:00:"
wait(0)
game.Lighting.TimeOfDay = "06:00:00:"
wait(0)
game.Lighting.TimeOfDay = "07:00:00:"
wait(0)
game.Lighting.TimeOfDay = "08:00:00:"
wait(0)
game.Lighting.TimeOfDay = "09:00:00:"
wait(0)
game.Lighting.TimeOfDay = "10:00:00:"
wait(0)
game.Lighting.TimeOfDay = "11:00:00:"
wait(0)
game.Lighting.TimeOfDay = "12:00:00:"
wait(0)
game.Lighting.TimeOfDay = "13:00:00:"
wait(0)
game.Lighting.TimeOfDay = "14:00:00:"
wait(0)
game.Lighting.TimeOfDay = "15:00:00:"
wait(0)
game.Lighting.TimeOfDay = "16:00:00:"
wait(0)
game.Lighting.TimeOfDay = "17:00:00:"
wait(0)
game.Lighting.TimeOfDay = "18:00:00:"
wait(0)
game.Lighting.TimeOfDay = "19:00:00:"
wait(0)
game.Lighting.TimeOfDay = "20:00:00:"
wait(0)
game.Lighting.TimeOfDay = "21:00:00:"
wait(0)
game.Lighting.TimeOfDay = "22:00:00:"
wait(0)
game.Lighting.TimeOfDay = "23:00:00:"
wait(0)
game.Lighting.TimeOfDay = "24:00:00:"game.Lighting.TimeOfDay = "00:00:00:"
wait(0)
game.Lighting.TimeOfDay = "01:00:00:"
wait(0)
game.Lighting.TimeOfDay = "02:00:00:"
wait(0)
game.Lighting.TimeOfDay = "03:00:00:"
wait(0)
game.Lighting.TimeOfDay = "04:00:00:"
wait(0)
game.Lighting.TimeOfDay = "05:00:00:"
wait(0)
game.Lighting.TimeOfDay = "06:00:00:"
wait(0)
game.Lighting.TimeOfDay = "07:00:00:"
wait(0)
game.Lighting.TimeOfDay = "08:00:00:"
wait(0)
game.Lighting.TimeOfDay = "09:00:00:"
wait(0)
game.Lighting.TimeOfDay = "10:00:00:"
wait(0)
game.Lighting.TimeOfDay = "11:00:00:"
wait(0)
game.Lighting.TimeOfDay = "12:00:00:"
wait(0)
game.Lighting.TimeOfDay = "13:00:00:"
wait(0)
game.Lighting.TimeOfDay = "14:00:00:"
wait(0)
game.Lighting.TimeOfDay = "15:00:00:"
wait(0)
game.Lighting.TimeOfDay = "16:00:00:"
wait(0)
game.Lighting.TimeOfDay = "17:00:00:"
wait(0)
game.Lighting.TimeOfDay = "18:00:00:"
wait(0)
game.Lighting.TimeOfDay = "19:00:00:"
wait(0)
game.Lighting.TimeOfDay = "20:00:00:"
wait(0)
game.Lighting.TimeOfDay = "21:00:00:"
wait(0)
game.Lighting.TimeOfDay = "22:00:00:"
wait(0)
game.Lighting.TimeOfDay = "23:00:00:"
wait(0)
game.Lighting.TimeOfDay = "24:00:00:"game.Lighting.TimeOfDay = "00:00:00:"
wait(0)
game.Lighting.TimeOfDay = "01:00:00:"
wait(0)
game.Lighting.TimeOfDay = "02:00:00:"
wait(0)
game.Lighting.TimeOfDay = "03:00:00:"
wait(0)
game.Lighting.TimeOfDay = "04:00:00:"
wait(0)
game.Lighting.TimeOfDay = "05:00:00:"
wait(0)
game.Lighting.TimeOfDay = "06:00:00:"
wait(0)
game.Lighting.TimeOfDay = "07:00:00:"
wait(0)
game.Lighting.TimeOfDay = "08:00:00:"
wait(0)
game.Lighting.TimeOfDay = "09:00:00:"
wait(0)
game.Lighting.TimeOfDay = "10:00:00:"
wait(0)
game.Lighting.TimeOfDay = "11:00:00:"
wait(0)
game.Lighting.TimeOfDay = "12:00:00:"
wait(0)
game.Lighting.TimeOfDay = "13:00:00:"
wait(0)
game.Lighting.TimeOfDay = "14:00:00:"
wait(0)
game.Lighting.TimeOfDay = "15:00:00:"
wait(0)
game.Lighting.TimeOfDay = "16:00:00:"
wait(0)
game.Lighting.TimeOfDay = "17:00:00:"
wait(0)
game.Lighting.TimeOfDay = "18:00:00:"
wait(0)
game.Lighting.TimeOfDay = "19:00:00:"
wait(0)
game.Lighting.TimeOfDay = "20:00:00:"
wait(0)
game.Lighting.TimeOfDay = "21:00:00:"
wait(0)
game.Lighting.TimeOfDay = "22:00:00:"
wait(0)
game.Lighting.TimeOfDay = "23:00:00:"
wait(0)
game.Lighting.TimeOfDay = "24:00:00:"game.Lighting.TimeOfDay = "00:00:00:"
wait(0)
game.Lighting.TimeOfDay = "01:00:00:"
wait(0)
game.Lighting.TimeOfDay = "02:00:00:"
wait(0)
game.Lighting.TimeOfDay = "03:00:00:"
wait(0)
game.Lighting.TimeOfDay = "04:00:00:"
wait(0)
game.Lighting.TimeOfDay = "05:00:00:"
wait(0)
game.Lighting.TimeOfDay = "06:00:00:"
wait(0)
game.Lighting.TimeOfDay = "07:00:00:"
wait(0)
game.Lighting.TimeOfDay = "08:00:00:"
wait(0)
game.Lighting.TimeOfDay = "09:00:00:"
wait(0)
game.Lighting.TimeOfDay = "10:00:00:"
wait(0)
game.Lighting.TimeOfDay = "11:00:00:"
wait(0)
game.Lighting.TimeOfDay = "12:00:00:"
wait(0)
game.Lighting.TimeOfDay = "13:00:00:"
wait(0)
game.Lighting.TimeOfDay = "14:00:00:"
wait(0)
game.Lighting.TimeOfDay = "15:00:00:"
wait(0)
game.Lighting.TimeOfDay = "16:00:00:"
wait(0)
game.Lighting.TimeOfDay = "17:00:00:"
wait(0)
game.Lighting.TimeOfDay = "18:00:00:"
wait(0)
game.Lighting.TimeOfDay = "19:00:00:"
wait(0)
game.Lighting.TimeOfDay = "20:00:00:"
wait(0)
game.Lighting.TimeOfDay = "21:00:00:"
wait(0)
game.Lighting.TimeOfDay = "22:00:00:"
wait(0)
game.Lighting.TimeOfDay = "23:00:00:"
wait(0)
game.Lighting.TimeOfDay = "24:00:00:"game.Lighting.TimeOfDay = "00:00:00:"
wait(0)
game.Lighting.TimeOfDay = "01:00:00:"
wait(0)
game.Lighting.TimeOfDay = "02:00:00:"
wait(0)
game.Lighting.TimeOfDay = "03:00:00:"
wait(0)
game.Lighting.TimeOfDay = "04:00:00:"
wait(0)
game.Lighting.TimeOfDay = "05:00:00:"
wait(0)
game.Lighting.TimeOfDay = "06:00:00:"
wait(0)
game.Lighting.TimeOfDay = "07:00:00:"
wait(0)
game.Lighting.TimeOfDay = "08:00:00:"
wait(0)
game.Lighting.TimeOfDay = "09:00:00:"
wait(0)
game.Lighting.TimeOfDay = "10:00:00:"
wait(0)
game.Lighting.TimeOfDay = "11:00:00:"
wait(0)
game.Lighting.TimeOfDay = "12:00:00:"
wait(0)
game.Lighting.TimeOfDay = "13:00:00:"
wait(0)
game.Lighting.TimeOfDay = "14:00:00:"
wait(0)
game.Lighting.TimeOfDay = "15:00:00:"
wait(0)
game.Lighting.TimeOfDay = "16:00:00:"
wait(0)
game.Lighting.TimeOfDay = "17:00:00:"
wait(0)
game.Lighting.TimeOfDay = "18:00:00:"
wait(0)
game.Lighting.TimeOfDay = "19:00:00:"
wait(0)
game.Lighting.TimeOfDay = "20:00:00:"
wait(0)
game.Lighting.TimeOfDay = "21:00:00:"
wait(0)
game.Lighting.TimeOfDay = "22:00:00:"
wait(0)
game.Lighting.TimeOfDay = "23:00:00:"
wait(0)
game.Lighting.TimeOfDay = "24:00:00:"game.Lighting.TimeOfDay = "00:00:00:"
wait(0)
game.Lighting.TimeOfDay = "01:00:00:"
wait(0)
game.Lighting.TimeOfDay = "02:00:00:"
wait(0)
game.Lighting.TimeOfDay = "03:00:00:"
wait(0)
game.Lighting.TimeOfDay = "04:00:00:"
wait(0)
game.Lighting.TimeOfDay = "05:00:00:"
wait(0)
game.Lighting.TimeOfDay = "06:00:00:"
wait(0)
game.Lighting.TimeOfDay = "07:00:00:"
wait(0)
game.Lighting.TimeOfDay = "08:00:00:"
wait(0)
game.Lighting.TimeOfDay = "09:00:00:"
wait(0)
game.Lighting.TimeOfDay = "10:00:00:"
wait(0)
game.Lighting.TimeOfDay = "11:00:00:"
wait(0)
game.Lighting.TimeOfDay = "12:00:00:"
wait(0)
game.Lighting.TimeOfDay = "13:00:00:"
wait(0)
game.Lighting.TimeOfDay = "14:00:00:"
wait(0)
game.Lighting.TimeOfDay = "15:00:00:"
wait(0)
game.Lighting.TimeOfDay = "16:00:00:"
wait(0)
game.Lighting.TimeOfDay = "17:00:00:"
wait(0)
game.Lighting.TimeOfDay = "18:00:00:"
wait(0)
game.Lighting.TimeOfDay = "19:00:00:"
wait(0)
game.Lighting.TimeOfDay = "20:00:00:"
wait(0)
game.Lighting.TimeOfDay = "21:00:00:"
wait(0)
game.Lighting.TimeOfDay = "22:00:00:"
wait(0)
game.Lighting.TimeOfDay = "23:00:00:"
wait(0)
game.Lighting.TimeOfDay = "24:00:00:"game.Lighting.TimeOfDay = "00:00:00:"
wait(0)
game.Lighting.TimeOfDay = "01:00:00:"
wait(0)
game.Lighting.TimeOfDay = "02:00:00:"
wait(0)
game.Lighting.TimeOfDay = "03:00:00:"
wait(0)
game.Lighting.TimeOfDay = "04:00:00:"
wait(0)
game.Lighting.TimeOfDay = "05:00:00:"
wait(0)
game.Lighting.TimeOfDay = "06:00:00:"
wait(0)
game.Lighting.TimeOfDay = "07:00:00:"
wait(0)
game.Lighting.TimeOfDay = "08:00:00:"
wait(0)
game.Lighting.TimeOfDay = "09:00:00:"
wait(0)
game.Lighting.TimeOfDay = "10:00:00:"
wait(0)
game.Lighting.TimeOfDay = "11:00:00:"
wait(0)
game.Lighting.TimeOfDay = "12:00:00:"
wait(0)
game.Lighting.TimeOfDay = "13:00:00:"
wait(0)
game.Lighting.TimeOfDay = "14:00:00:"
wait(0)
game.Lighting.TimeOfDay = "15:00:00:"
wait(0)
game.Lighting.TimeOfDay = "16:00:00:"
wait(0)
game.Lighting.TimeOfDay = "17:00:00:"
wait(0)
game.Lighting.TimeOfDay = "18:00:00:"
wait(0)
game.Lighting.TimeOfDay = "19:00:00:"
wait(0)
game.Lighting.TimeOfDay = "20:00:00:"
wait(0)
game.Lighting.TimeOfDay = "21:00:00:"
wait(0)
game.Lighting.TimeOfDay = "22:00:00:"
wait(0)
game.Lighting.TimeOfDay = "23:00:00:"
wait(0)
game.Lighting.TimeOfDay = "24:00:00:"game.Lighting.TimeOfDay = "00:00:00:"
wait(0)
game.Lighting.TimeOfDay = "01:00:00:"
wait(0)
game.Lighting.TimeOfDay = "02:00:00:"
wait(0)
game.Lighting.TimeOfDay = "03:00:00:"
wait(0)
game.Lighting.TimeOfDay = "04:00:00:"
wait(0)
game.Lighting.TimeOfDay = "05:00:00:"
wait(0)
game.Lighting.TimeOfDay = "06:00:00:"
wait(0)
game.Lighting.TimeOfDay = "07:00:00:"
wait(0)
game.Lighting.TimeOfDay = "08:00:00:"
wait(0)
game.Lighting.TimeOfDay = "09:00:00:"
wait(0)
game.Lighting.TimeOfDay = "10:00:00:"
wait(0)
game.Lighting.TimeOfDay = "11:00:00:"
wait(0)
game.Lighting.TimeOfDay = "12:00:00:"
wait(0)
game.Lighting.TimeOfDay = "13:00:00:"
wait(0)
game.Lighting.TimeOfDay = "14:00:00:"
wait(0)
game.Lighting.TimeOfDay = "15:00:00:"
wait(0)
game.Lighting.TimeOfDay = "16:00:00:"
wait(0)
game.Lighting.TimeOfDay = "17:00:00:"
wait(0)
game.Lighting.TimeOfDay = "18:00:00:"
wait(0)
game.Lighting.TimeOfDay = "19:00:00:"
wait(0)
game.Lighting.TimeOfDay = "20:00:00:"
wait(0)
game.Lighting.TimeOfDay = "21:00:00:"
wait(0)
game.Lighting.TimeOfDay = "22:00:00:"
wait(0)
game.Lighting.TimeOfDay = "23:00:00:"
wait(0)
game.Lighting.TimeOfDay = "24:00:00:"game.Lighting.TimeOfDay = "00:00:00:"
wait(0)
game.Lighting.TimeOfDay = "01:00:00:"
wait(0)
game.Lighting.TimeOfDay = "02:00:00:"
wait(0)
game.Lighting.TimeOfDay = "03:00:00:"
wait(0)
game.Lighting.TimeOfDay = "04:00:00:"
wait(0)
game.Lighting.TimeOfDay = "05:00:00:"
wait(0)
game.Lighting.TimeOfDay = "06:00:00:"
wait(0)
game.Lighting.TimeOfDay = "07:00:00:"
wait(0)
game.Lighting.TimeOfDay = "08:00:00:"
wait(0)
game.Lighting.TimeOfDay = "09:00:00:"
wait(0)
game.Lighting.TimeOfDay = "10:00:00:"
wait(0)
game.Lighting.TimeOfDay = "11:00:00:"
wait(0)
game.Lighting.TimeOfDay = "12:00:00:"
wait(0)
game.Lighting.TimeOfDay = "13:00:00:"
wait(0)
game.Lighting.TimeOfDay = "14:00:00:"
wait(0)
game.Lighting.TimeOfDay = "15:00:00:"
wait(0)
game.Lighting.TimeOfDay = "16:00:00:"
wait(0)
game.Lighting.TimeOfDay = "17:00:00:"
wait(0)
game.Lighting.TimeOfDay = "18:00:00:"
wait(0)
game.Lighting.TimeOfDay = "19:00:00:"
wait(0)
game.Lighting.TimeOfDay = "20:00:00:"
wait(0)
game.Lighting.TimeOfDay = "21:00:00:"
wait(0)
game.Lighting.TimeOfDay = "22:00:00:"
wait(0)
game.Lighting.TimeOfDay = "23:00:00:"
wait(0)
game.Lighting.TimeOfDay = "24:00:00:"game.Lighting.TimeOfDay = "00:00:00:"
wait(0)
game.Lighting.TimeOfDay = "01:00:00:"
wait(0)
game.Lighting.TimeOfDay = "02:00:00:"
wait(0)
game.Lighting.TimeOfDay = "03:00:00:"
wait(0)
game.Lighting.TimeOfDay = "04:00:00:"
wait(0)
game.Lighting.TimeOfDay = "05:00:00:"
wait(0)
game.Lighting.TimeOfDay = "06:00:00:"
wait(0)
game.Lighting.TimeOfDay = "07:00:00:"
wait(0)
game.Lighting.TimeOfDay = "08:00:00:"
wait(0)
game.Lighting.TimeOfDay = "09:00:00:"
wait(0)
game.Lighting.TimeOfDay = "10:00:00:"
wait(0)
game.Lighting.TimeOfDay = "11:00:00:"
wait(0)
game.Lighting.TimeOfDay = "12:00:00:"
wait(0)
game.Lighting.TimeOfDay = "13:00:00:"
wait(0)
game.Lighting.TimeOfDay = "14:00:00:"
wait(0)
game.Lighting.TimeOfDay = "15:00:00:"
wait(0)
game.Lighting.TimeOfDay = "16:00:00:"
wait(0)
game.Lighting.TimeOfDay = "17:00:00:"
wait(0)
game.Lighting.TimeOfDay = "18:00:00:"
wait(0)
game.Lighting.TimeOfDay = "19:00:00:"
wait(0)
game.Lighting.TimeOfDay = "20:00:00:"
wait(0)
game.Lighting.TimeOfDay = "21:00:00:"
wait(0)
game.Lighting.TimeOfDay = "22:00:00:"
wait(0)
game.Lighting.TimeOfDay = "23:00:00:"
wait(0)
game.Lighting.TimeOfDay = "24:00:00:"game.Lighting.TimeOfDay = "00:00:00:"
wait(0)
game.Lighting.TimeOfDay = "01:00:00:"
wait(0)
game.Lighting.TimeOfDay = "02:00:00:"
wait(0)
game.Lighting.TimeOfDay = "03:00:00:"
wait(0)
game.Lighting.TimeOfDay = "04:00:00:"
wait(0)
game.Lighting.TimeOfDay = "05:00:00:"
wait(0)
game.Lighting.TimeOfDay = "06:00:00:"
wait(0)
game.Lighting.TimeOfDay = "07:00:00:"
wait(0)
game.Lighting.TimeOfDay = "08:00:00:"
wait(0)
game.Lighting.TimeOfDay = "09:00:00:"
wait(0)
game.Lighting.TimeOfDay = "10:00:00:"
wait(0)
game.Lighting.TimeOfDay = "11:00:00:"
wait(0)
game.Lighting.TimeOfDay = "12:00:00:"
wait(0)
game.Lighting.TimeOfDay = "13:00:00:"
wait(0)
game.Lighting.TimeOfDay = "14:00:00:"
wait(0)
game.Lighting.TimeOfDay = "15:00:00:"
wait(0)
game.Lighting.TimeOfDay = "16:00:00:"
wait(0)
game.Lighting.TimeOfDay = "17:00:00:"
wait(0)
game.Lighting.TimeOfDay = "18:00:00:"
wait(0)
game.Lighting.TimeOfDay = "19:00:00:"
wait(0)
game.Lighting.TimeOfDay = "20:00:00:"
wait(0)
game.Lighting.TimeOfDay = "21:00:00:"
wait(0)
game.Lighting.TimeOfDay = "22:00:00:"
wait(0)
game.Lighting.TimeOfDay = "23:00:00:"
wait(0)
game.Lighting.TimeOfDay = "24:00:00:"game.Lighting.TimeOfDay = "00:00:00:"
wait(0)
game.Lighting.TimeOfDay = "01:00:00:"
wait(0)
game.Lighting.TimeOfDay = "02:00:00:"
wait(0)
game.Lighting.TimeOfDay = "03:00:00:"
wait(0)
game.Lighting.TimeOfDay = "04:00:00:"
wait(0)
game.Lighting.TimeOfDay = "05:00:00:"
wait(0)
game.Lighting.TimeOfDay = "06:00:00:"
wait(0)
game.Lighting.TimeOfDay = "07:00:00:"
wait(0)
game.Lighting.TimeOfDay = "08:00:00:"
wait(0)
game.Lighting.TimeOfDay = "09:00:00:"
wait(0)
game.Lighting.TimeOfDay = "10:00:00:"
wait(0)
game.Lighting.TimeOfDay = "11:00:00:"
wait(0)
game.Lighting.TimeOfDay = "12:00:00:"
wait(0)
game.Lighting.TimeOfDay = "13:00:00:"
wait(0)
game.Lighting.TimeOfDay = "14:00:00:"
wait(0)
game.Lighting.TimeOfDay = "15:00:00:"
wait(0)
game.Lighting.TimeOfDay = "16:00:00:"
wait(0)
game.Lighting.TimeOfDay = "17:00:00:"
wait(0)
game.Lighting.TimeOfDay = "18:00:00:"
wait(0)
game.Lighting.TimeOfDay = "19:00:00:"
wait(0)
game.Lighting.TimeOfDay = "20:00:00:"
wait(0)
game.Lighting.TimeOfDay = "21:00:00:"
wait(0)
game.Lighting.TimeOfDay = "22:00:00:"
wait(0)
game.Lighting.TimeOfDay = "23:00:00:"
wait(0)
game.Lighting.TimeOfDay = "24:00:00:"game.Lighting.TimeOfDay = "00:00:00:"
wait(0)
game.Lighting.TimeOfDay = "01:00:00:"
wait(0)
game.Lighting.TimeOfDay = "02:00:00:"
wait(0)
game.Lighting.TimeOfDay = "03:00:00:"
wait(0)
game.Lighting.TimeOfDay = "04:00:00:"
wait(0)
game.Lighting.TimeOfDay = "05:00:00:"
wait(0)
game.Lighting.TimeOfDay = "06:00:00:"
wait(0)
game.Lighting.TimeOfDay = "07:00:00:"
wait(0)
game.Lighting.TimeOfDay = "08:00:00:"
wait(0)
game.Lighting.TimeOfDay = "09:00:00:"
wait(0)
game.Lighting.TimeOfDay = "10:00:00:"
wait(0)
game.Lighting.TimeOfDay = "11:00:00:"
wait(0)
game.Lighting.TimeOfDay = "12:00:00:"
wait(0)
game.Lighting.TimeOfDay = "13:00:00:"
wait(0)
game.Lighting.TimeOfDay = "14:00:00:"
wait(0)
game.Lighting.TimeOfDay = "15:00:00:"
wait(0)
game.Lighting.TimeOfDay = "16:00:00:"
wait(0)
game.Lighting.TimeOfDay = "17:00:00:"
wait(0)
game.Lighting.TimeOfDay = "18:00:00:"
wait(0)
game.Lighting.TimeOfDay = "19:00:00:"
wait(0)
game.Lighting.TimeOfDay = "20:00:00:"
wait(0)
game.Lighting.TimeOfDay = "21:00:00:"
wait(0)
game.Lighting.TimeOfDay = "22:00:00:"
wait(0)
game.Lighting.TimeOfDay = "23:00:00:"
wait(0)
game.Lighting.TimeOfDay = "24:00:00:"
game.Lighting.TimeOfDay = "00:00:00:"
wait(0)
game.Lighting.TimeOfDay = "01:00:00:"
wait(0)
game.Lighting.TimeOfDay = "02:00:00:"
wait(0)
game.Lighting.TimeOfDay = "03:00:00:"
wait(0)
game.Lighting.TimeOfDay = "04:00:00:"
wait(0)
game.Lighting.TimeOfDay = "05:00:00:"
wait(0)
game.Lighting.TimeOfDay = "06:00:00:"
wait(0)
game.Lighting.TimeOfDay = "07:00:00:"
wait(0)
game.Lighting.TimeOfDay = "08:00:00:"
wait(0)
game.Lighting.TimeOfDay = "09:00:00:"
wait(0)
game.Lighting.TimeOfDay = "10:00:00:"
wait(0)
game.Lighting.TimeOfDay = "11:00:00:"
wait(0)
game.Lighting.TimeOfDay = "12:00:00:"
wait(0)
game.Lighting.TimeOfDay = "13:00:00:"
wait(0)
game.Lighting.TimeOfDay = "14:00:00:"
wait(0)
game.Lighting.TimeOfDay = "15:00:00:"
wait(0)
game.Lighting.TimeOfDay = "16:00:00:"
wait(0)
game.Lighting.TimeOfDay = "17:00:00:"
wait(0)
game.Lighting.TimeOfDay = "18:00:00:"
wait(0)
game.Lighting.TimeOfDay = "19:00:00:"
wait(0)
game.Lighting.TimeOfDay = "20:00:00:"
wait(0)
game.Lighting.TimeOfDay = "21:00:00:"
wait(0)
game.Lighting.TimeOfDay = "22:00:00:"
wait(0)
game.Lighting.TimeOfDay = "23:00:00:"
wait(0)
game.Lighting.TimeOfDay = "24:00:00:"game.Lighting.TimeOfDay = "00:00:00:"
wait(0)
game.Lighting.TimeOfDay = "01:00:00:"
wait(0)
game.Lighting.TimeOfDay = "02:00:00:"
wait(0)
game.Lighting.TimeOfDay = "03:00:00:"
wait(0)
game.Lighting.TimeOfDay = "04:00:00:"
wait(0)
game.Lighting.TimeOfDay = "05:00:00:"
wait(0)
game.Lighting.TimeOfDay = "06:00:00:"
wait(0)
game.Lighting.TimeOfDay = "07:00:00:"
wait(0)
game.Lighting.TimeOfDay = "08:00:00:"
wait(0)
game.Lighting.TimeOfDay = "09:00:00:"
wait(0)
game.Lighting.TimeOfDay = "10:00:00:"
wait(0)
game.Lighting.TimeOfDay = "11:00:00:"
wait(0)
game.Lighting.TimeOfDay = "12:00:00:"
wait(0)
game.Lighting.TimeOfDay = "13:00:00:"
wait(0)
game.Lighting.TimeOfDay = "14:00:00:"
wait(0)
game.Lighting.TimeOfDay = "15:00:00:"
wait(0)
game.Lighting.TimeOfDay = "16:00:00:"
wait(0)
game.Lighting.TimeOfDay = "17:00:00:"
wait(0)
game.Lighting.TimeOfDay = "18:00:00:"
wait(0)
game.Lighting.TimeOfDay = "19:00:00:"
wait(0)
game.Lighting.TimeOfDay = "20:00:00:"
wait(0)
game.Lighting.TimeOfDay = "21:00:00:"
wait(0)
game.Lighting.TimeOfDay = "22:00:00:"
wait(0)
game.Lighting.TimeOfDay = "23:00:00:"
wait(0)
game.Lighting.TimeOfDay = "24:00:00:"game.Lighting.TimeOfDay = "00:00:00:"
wait(0)
game.Lighting.TimeOfDay = "01:00:00:"
wait(0)
game.Lighting.TimeOfDay = "02:00:00:"
wait(0)
game.Lighting.TimeOfDay = "03:00:00:"
wait(0)
game.Lighting.TimeOfDay = "04:00:00:"
wait(0)
game.Lighting.TimeOfDay = "05:00:00:"
wait(0)
game.Lighting.TimeOfDay = "06:00:00:"
wait(0)
game.Lighting.TimeOfDay = "07:00:00:"
wait(0)
game.Lighting.TimeOfDay = "08:00:00:"
wait(0)
game.Lighting.TimeOfDay = "09:00:00:"
wait(0)
game.Lighting.TimeOfDay = "10:00:00:"
wait(0)
game.Lighting.TimeOfDay = "11:00:00:"
wait(0)
game.Lighting.TimeOfDay = "12:00:00:"
wait(0)
game.Lighting.TimeOfDay = "13:00:00:"
wait(0)
game.Lighting.TimeOfDay = "14:00:00:"
wait(0)
game.Lighting.TimeOfDay = "15:00:00:"
wait(0)
game.Lighting.TimeOfDay = "16:00:00:"
wait(0)
game.Lighting.TimeOfDay = "17:00:00:"
wait(0)
game.Lighting.TimeOfDay = "18:00:00:"
wait(0)
game.Lighting.TimeOfDay = "19:00:00:"
wait(0)
game.Lighting.TimeOfDay = "20:00:00:"
wait(0)
game.Lighting.TimeOfDay = "21:00:00:"
wait(0)
game.Lighting.TimeOfDay = "22:00:00:"
wait(0)
game.Lighting.TimeOfDay = "23:00:00:"
wait(0)
game.Lighting.TimeOfDay = "24:00:00:"game.Lighting.TimeOfDay = "00:00:00:"
wait(0)
game.Lighting.TimeOfDay = "01:00:00:"
wait(0)
game.Lighting.TimeOfDay = "02:00:00:"
wait(0)
game.Lighting.TimeOfDay = "03:00:00:"
wait(0)
game.Lighting.TimeOfDay = "04:00:00:"
wait(0)
game.Lighting.TimeOfDay = "05:00:00:"
wait(0)
game.Lighting.TimeOfDay = "06:00:00:"
wait(0)
game.Lighting.TimeOfDay = "07:00:00:"
wait(0)
game.Lighting.TimeOfDay = "08:00:00:"
wait(0)
game.Lighting.TimeOfDay = "09:00:00:"
wait(0)
game.Lighting.TimeOfDay = "10:00:00:"
wait(0)
game.Lighting.TimeOfDay = "11:00:00:"
wait(0)
game.Lighting.TimeOfDay = "12:00:00:"
wait(0)
game.Lighting.TimeOfDay = "13:00:00:"
wait(0)
game.Lighting.TimeOfDay = "14:00:00:"
wait(0)
game.Lighting.TimeOfDay = "15:00:00:"
wait(0)
game.Lighting.TimeOfDay = "16:00:00:"
wait(0)
game.Lighting.TimeOfDay = "17:00:00:"
wait(0)
game.Lighting.TimeOfDay = "18:00:00:"
wait(0)
game.Lighting.TimeOfDay = "19:00:00:"
wait(0)
game.Lighting.TimeOfDay = "20:00:00:"
wait(0)
game.Lighting.TimeOfDay = "21:00:00:"
wait(0)
game.Lighting.TimeOfDay = "22:00:00:"
wait(0)
game.Lighting.TimeOfDay = "23:00:00:"
wait(0)
game.Lighting.TimeOfDay = "24:00:00:"game.Lighting.TimeOfDay = "00:00:00:"
wait(0)
game.Lighting.TimeOfDay = "01:00:00:"
wait(0)
game.Lighting.TimeOfDay = "02:00:00:"
wait(0)
game.Lighting.TimeOfDay = "03:00:00:"
wait(0)
game.Lighting.TimeOfDay = "04:00:00:"
wait(0)
game.Lighting.TimeOfDay = "05:00:00:"
wait(0)
game.Lighting.TimeOfDay = "06:00:00:"
wait(0)
game.Lighting.TimeOfDay = "07:00:00:"
wait(0)
game.Lighting.TimeOfDay = "08:00:00:"
wait(0)
game.Lighting.TimeOfDay = "09:00:00:"
wait(0)
game.Lighting.TimeOfDay = "10:00:00:"
wait(0)
game.Lighting.TimeOfDay = "11:00:00:"
wait(0)
game.Lighting.TimeOfDay = "12:00:00:"
wait(0)
game.Lighting.TimeOfDay = "13:00:00:"
wait(0)
game.Lighting.TimeOfDay = "14:00:00:"
wait(0)
game.Lighting.TimeOfDay = "15:00:00:"
wait(0)
game.Lighting.TimeOfDay = "16:00:00:"
wait(0)
game.Lighting.TimeOfDay = "17:00:00:"
wait(0)
game.Lighting.TimeOfDay = "18:00:00:"
wait(0)
game.Lighting.TimeOfDay = "19:00:00:"
wait(0)
game.Lighting.TimeOfDay = "20:00:00:"
wait(0)
game.Lighting.TimeOfDay = "21:00:00:"
wait(0)
game.Lighting.TimeOfDay = "22:00:00:"
wait(0)
game.Lighting.TimeOfDay = "23:00:00:"
wait(0)
game.Lighting.TimeOfDay = "24:00:00:"game.Lighting.TimeOfDay = "00:00:00:"
wait(0)
game.Lighting.TimeOfDay = "01:00:00:"
wait(0)
game.Lighting.TimeOfDay = "02:00:00:"
wait(0)
game.Lighting.TimeOfDay = "03:00:00:"
wait(0)
game.Lighting.TimeOfDay = "04:00:00:"
wait(0)
game.Lighting.TimeOfDay = "05:00:00:"
wait(0)
game.Lighting.TimeOfDay = "06:00:00:"
wait(0)
game.Lighting.TimeOfDay = "07:00:00:"
wait(0)
game.Lighting.TimeOfDay = "08:00:00:"
wait(0)
game.Lighting.TimeOfDay = "09:00:00:"
wait(0)
game.Lighting.TimeOfDay = "10:00:00:"
wait(0)
game.Lighting.TimeOfDay = "11:00:00:"
wait(0)
game.Lighting.TimeOfDay = "12:00:00:"
wait(0)
game.Lighting.TimeOfDay = "13:00:00:"
wait(0)
game.Lighting.TimeOfDay = "14:00:00:"
wait(0)
game.Lighting.TimeOfDay = "15:00:00:"
wait(0)
game.Lighting.TimeOfDay = "16:00:00:"
wait(0)
game.Lighting.TimeOfDay = "17:00:00:"
wait(0)
game.Lighting.TimeOfDay = "18:00:00:"
wait(0)
game.Lighting.TimeOfDay = "19:00:00:"
wait(0)
game.Lighting.TimeOfDay = "20:00:00:"
wait(0)
game.Lighting.TimeOfDay = "21:00:00:"
wait(0)
game.Lighting.TimeOfDay = "22:00:00:"
wait(0)
game.Lighting.TimeOfDay = "23:00:00:"
wait(0)
game.Lighting.TimeOfDay = "24:00:00:"game.Lighting.TimeOfDay = "00:00:00:"
wait(0)
game.Lighting.TimeOfDay = "01:00:00:"
wait(0)
game.Lighting.TimeOfDay = "02:00:00:"
wait(0)
game.Lighting.TimeOfDay = "03:00:00:"
wait(0)
game.Lighting.TimeOfDay = "04:00:00:"
wait(0)
game.Lighting.TimeOfDay = "05:00:00:"
wait(0)
game.Lighting.TimeOfDay = "06:00:00:"
wait(0)
game.Lighting.TimeOfDay = "07:00:00:"
wait(0)
game.Lighting.TimeOfDay = "08:00:00:"
wait(0)
game.Lighting.TimeOfDay = "09:00:00:"
wait(0)
game.Lighting.TimeOfDay = "10:00:00:"
wait(0)
game.Lighting.TimeOfDay = "11:00:00:"
wait(0)
game.Lighting.TimeOfDay = "12:00:00:"
wait(0)
game.Lighting.TimeOfDay = "13:00:00:"
wait(0)
game.Lighting.TimeOfDay = "14:00:00:"
wait(0)
game.Lighting.TimeOfDay = "15:00:00:"
wait(0)
game.Lighting.TimeOfDay = "16:00:00:"
wait(0)
game.Lighting.TimeOfDay = "17:00:00:"
wait(0)
game.Lighting.TimeOfDay = "18:00:00:"
wait(0)
game.Lighting.TimeOfDay = "19:00:00:"
wait(0)
game.Lighting.TimeOfDay = "20:00:00:"
wait(0)
game.Lighting.TimeOfDay = "21:00:00:"
wait(0)
game.Lighting.TimeOfDay = "22:00:00:"
wait(0)
game.Lighting.TimeOfDay = "23:00:00:"
wait(0)
game.Lighting.TimeOfDay = "24:00:00:"game.Lighting.TimeOfDay = "00:00:00:"
wait(0)
game.Lighting.TimeOfDay = "01:00:00:"
wait(0)
game.Lighting.TimeOfDay = "02:00:00:"
wait(0)
game.Lighting.TimeOfDay = "03:00:00:"
wait(0)
game.Lighting.TimeOfDay = "04:00:00:"
wait(0)
game.Lighting.TimeOfDay = "05:00:00:"
wait(0)
game.Lighting.TimeOfDay = "06:00:00:"
wait(0)
game.Lighting.TimeOfDay = "07:00:00:"
wait(0)
game.Lighting.TimeOfDay = "08:00:00:"
wait(0)
game.Lighting.TimeOfDay = "09:00:00:"
wait(0)
game.Lighting.TimeOfDay = "10:00:00:"
wait(0)
game.Lighting.TimeOfDay = "11:00:00:"
wait(0)
game.Lighting.TimeOfDay = "12:00:00:"
wait(0)
game.Lighting.TimeOfDay = "13:00:00:"
wait(0)
game.Lighting.TimeOfDay = "14:00:00:"
wait(0)
game.Lighting.TimeOfDay = "15:00:00:"
wait(0)
game.Lighting.TimeOfDay = "16:00:00:"
wait(0)
game.Lighting.TimeOfDay = "17:00:00:"
wait(0)
game.Lighting.TimeOfDay = "18:00:00:"
wait(0)
game.Lighting.TimeOfDay = "19:00:00:"
wait(0)
game.Lighting.TimeOfDay = "20:00:00:"
wait(0)
game.Lighting.TimeOfDay = "21:00:00:"
wait(0)
game.Lighting.TimeOfDay = "22:00:00:"
wait(0)
game.Lighting.TimeOfDay = "23:00:00:"
wait(0)
game.Lighting.TimeOfDay = "24:00:00:"game.Lighting.TimeOfDay = "00:00:00:"
wait(0)
game.Lighting.TimeOfDay = "01:00:00:"
wait(0)
game.Lighting.TimeOfDay = "02:00:00:"
wait(0)
game.Lighting.TimeOfDay = "03:00:00:"
wait(0)
game.Lighting.TimeOfDay = "04:00:00:"
wait(0)
game.Lighting.TimeOfDay = "05:00:00:"
wait(0)
game.Lighting.TimeOfDay = "06:00:00:"
wait(0)
game.Lighting.TimeOfDay = "07:00:00:"
wait(0)
game.Lighting.TimeOfDay = "08:00:00:"
wait(0)
game.Lighting.TimeOfDay = "09:00:00:"
wait(0)
game.Lighting.TimeOfDay = "10:00:00:"
wait(0)
game.Lighting.TimeOfDay = "11:00:00:"
wait(0)
game.Lighting.TimeOfDay = "12:00:00:"
wait(0)
game.Lighting.TimeOfDay = "13:00:00:"
wait(0)
game.Lighting.TimeOfDay = "14:00:00:"
wait(0)
game.Lighting.TimeOfDay = "15:00:00:"
wait(0)
game.Lighting.TimeOfDay = "16:00:00:"
wait(0)
game.Lighting.TimeOfDay = "17:00:00:"
wait(0)
game.Lighting.TimeOfDay = "18:00:00:"
wait(0)
game.Lighting.TimeOfDay = "19:00:00:"
wait(0)
game.Lighting.TimeOfDay = "20:00:00:"
wait(0)
game.Lighting.TimeOfDay = "21:00:00:"
wait(0)
game.Lighting.TimeOfDay = "22:00:00:"
wait(0)
game.Lighting.TimeOfDay = "23:00:00:"
wait(0)
game.Lighting.TimeOfDay = "24:00:00:"game.Lighting.TimeOfDay = "00:00:00:"
wait(0)
game.Lighting.TimeOfDay = "01:00:00:"
wait(0)
game.Lighting.TimeOfDay = "02:00:00:"
wait(0)
game.Lighting.TimeOfDay = "03:00:00:"
wait(0)
game.Lighting.TimeOfDay = "04:00:00:"
wait(0)
game.Lighting.TimeOfDay = "05:00:00:"
wait(0)
game.Lighting.TimeOfDay = "06:00:00:"
wait(0)
game.Lighting.TimeOfDay = "07:00:00:"
wait(0)
game.Lighting.TimeOfDay = "08:00:00:"
wait(0)
game.Lighting.TimeOfDay = "09:00:00:"
wait(0)
game.Lighting.TimeOfDay = "10:00:00:"
wait(0)
game.Lighting.TimeOfDay = "11:00:00:"
wait(0)
game.Lighting.TimeOfDay = "12:00:00:"
wait(0)
game.Lighting.TimeOfDay = "13:00:00:"
wait(0)
game.Lighting.TimeOfDay = "14:00:00:"
wait(0)
game.Lighting.TimeOfDay = "15:00:00:"
wait(0)
game.Lighting.TimeOfDay = "16:00:00:"
wait(0)
game.Lighting.TimeOfDay = "17:00:00:"
wait(0)
game.Lighting.TimeOfDay = "18:00:00:"
wait(0)
game.Lighting.TimeOfDay = "19:00:00:"
wait(0)
game.Lighting.TimeOfDay = "20:00:00:"
wait(0)
game.Lighting.TimeOfDay = "21:00:00:"
wait(0)
game.Lighting.TimeOfDay = "22:00:00:"
wait(0)
game.Lighting.TimeOfDay = "23:00:00:"
wait(0)
game.Lighting.TimeOfDay = "24:00:00:"game.Lighting.TimeOfDay = "00:00:00:"
wait(0)
game.Lighting.TimeOfDay = "01:00:00:"
wait(0)
game.Lighting.TimeOfDay = "02:00:00:"
wait(0)
game.Lighting.TimeOfDay = "03:00:00:"
wait(0)
game.Lighting.TimeOfDay = "04:00:00:"
wait(0)
game.Lighting.TimeOfDay = "05:00:00:"
wait(0)
game.Lighting.TimeOfDay = "06:00:00:"
wait(0)
game.Lighting.TimeOfDay = "07:00:00:"
wait(0)
game.Lighting.TimeOfDay = "08:00:00:"
wait(0)
game.Lighting.TimeOfDay = "09:00:00:"
wait(0)
game.Lighting.TimeOfDay = "10:00:00:"
wait(0)
game.Lighting.TimeOfDay = "11:00:00:"
wait(0)
game.Lighting.TimeOfDay = "12:00:00:"
wait(0)
game.Lighting.TimeOfDay = "13:00:00:"
wait(0)
game.Lighting.TimeOfDay = "14:00:00:"
wait(0)
game.Lighting.TimeOfDay = "15:00:00:"
wait(0)
game.Lighting.TimeOfDay = "16:00:00:"
wait(0)
game.Lighting.TimeOfDay = "17:00:00:"
wait(0)
game.Lighting.TimeOfDay = "18:00:00:"
wait(0)
game.Lighting.TimeOfDay = "19:00:00:"
wait(0)
game.Lighting.TimeOfDay = "20:00:00:"
wait(0)
game.Lighting.TimeOfDay = "21:00:00:"
wait(0)
game.Lighting.TimeOfDay = "22:00:00:"
wait(0)
game.Lighting.TimeOfDay = "23:00:00:"
wait(0)
game.Lighting.TimeOfDay = "24:00:00:"game.Lighting.TimeOfDay = "00:00:00:"
wait(0)
game.Lighting.TimeOfDay = "01:00:00:"
wait(0)
game.Lighting.TimeOfDay = "02:00:00:"
wait(0)
game.Lighting.TimeOfDay = "03:00:00:"
wait(0)
game.Lighting.TimeOfDay = "04:00:00:"
wait(0)
game.Lighting.TimeOfDay = "05:00:00:"
wait(0)
game.Lighting.TimeOfDay = "06:00:00:"
wait(0)
game.Lighting.TimeOfDay = "07:00:00:"
wait(0)
game.Lighting.TimeOfDay = "08:00:00:"
wait(0)
game.Lighting.TimeOfDay = "09:00:00:"
wait(0)
game.Lighting.TimeOfDay = "10:00:00:"
wait(0)
game.Lighting.TimeOfDay = "11:00:00:"
wait(0)
game.Lighting.TimeOfDay = "12:00:00:"
wait(0)
game.Lighting.TimeOfDay = "13:00:00:"
wait(0)
game.Lighting.TimeOfDay = "14:00:00:"
wait(0)
game.Lighting.TimeOfDay = "15:00:00:"
wait(0)
game.Lighting.TimeOfDay = "16:00:00:"
wait(0)
game.Lighting.TimeOfDay = "17:00:00:"
wait(0)
game.Lighting.TimeOfDay = "18:00:00:"
wait(0)
game.Lighting.TimeOfDay = "19:00:00:"
wait(0)
game.Lighting.TimeOfDay = "20:00:00:"
wait(0)
game.Lighting.TimeOfDay = "21:00:00:"
wait(0)
game.Lighting.TimeOfDay = "22:00:00:"
wait(0)
game.Lighting.TimeOfDay = "23:00:00:"
wait(0)
game.Lighting.TimeOfDay = "24:00:00:"game.Lighting.TimeOfDay = "00:00:00:"
wait(0)
game.Lighting.TimeOfDay = "01:00:00:"
wait(0)
game.Lighting.TimeOfDay = "02:00:00:"
wait(0)
game.Lighting.TimeOfDay = "03:00:00:"
wait(0)
game.Lighting.TimeOfDay = "04:00:00:"
wait(0)
game.Lighting.TimeOfDay = "05:00:00:"
wait(0)
game.Lighting.TimeOfDay = "06:00:00:"
wait(0)
game.Lighting.TimeOfDay = "07:00:00:"
wait(0)
game.Lighting.TimeOfDay = "08:00:00:"
wait(0)
game.Lighting.TimeOfDay = "09:00:00:"
wait(0)
game.Lighting.TimeOfDay = "10:00:00:"
wait(0)
game.Lighting.TimeOfDay = "11:00:00:"
wait(0)
game.Lighting.TimeOfDay = "12:00:00:"
wait(0)
game.Lighting.TimeOfDay = "13:00:00:"
wait(0)
game.Lighting.TimeOfDay = "14:00:00:"
wait(0)
game.Lighting.TimeOfDay = "15:00:00:"
wait(0)
game.Lighting.TimeOfDay = "16:00:00:"
wait(0)
game.Lighting.TimeOfDay = "17:00:00:"
wait(0)
game.Lighting.TimeOfDay = "18:00:00:"
wait(0)
game.Lighting.TimeOfDay = "19:00:00:"
wait(0)
game.Lighting.TimeOfDay = "20:00:00:"
wait(0)
game.Lighting.TimeOfDay = "21:00:00:"
wait(0)
game.Lighting.TimeOfDay = "22:00:00:"
wait(0)
game.Lighting.TimeOfDay = "23:00:00:"
wait(0)
game.Lighting.TimeOfDay = "24:00:00:"game.Lighting.TimeOfDay = "00:00:00:"
wait(0)
game.Lighting.TimeOfDay = "01:00:00:"
wait(0)
game.Lighting.TimeOfDay = "02:00:00:"
wait(0)
game.Lighting.TimeOfDay = "03:00:00:"
wait(0)
game.Lighting.TimeOfDay = "04:00:00:"
wait(0)
game.Lighting.TimeOfDay = "05:00:00:"
wait(0)
game.Lighting.TimeOfDay = "06:00:00:"
wait(0)
game.Lighting.TimeOfDay = "07:00:00:"
wait(0)
game.Lighting.TimeOfDay = "08:00:00:"
wait(0)
game.Lighting.TimeOfDay = "09:00:00:"
wait(0)
game.Lighting.TimeOfDay = "10:00:00:"
wait(0)
game.Lighting.TimeOfDay = "11:00:00:"
wait(0)
game.Lighting.TimeOfDay = "12:00:00:"
wait(0)
game.Lighting.TimeOfDay = "13:00:00:"
wait(0)
game.Lighting.TimeOfDay = "14:00:00:"
wait(0)
game.Lighting.TimeOfDay = "15:00:00:"
wait(0)
game.Lighting.TimeOfDay = "16:00:00:"
wait(0)
game.Lighting.TimeOfDay = "17:00:00:"
wait(0)
game.Lighting.TimeOfDay = "18:00:00:"
wait(0)
game.Lighting.TimeOfDay = "19:00:00:"
wait(0)
game.Lighting.TimeOfDay = "20:00:00:"
wait(0)
game.Lighting.TimeOfDay = "21:00:00:"
wait(0)
game.Lighting.TimeOfDay = "22:00:00:"
wait(0)
game.Lighting.TimeOfDay = "23:00:00:"
wait(0)
game.Lighting.TimeOfDay = "24:00:00:"game.Lighting.TimeOfDay = "00:00:00:"
wait(0)
game.Lighting.TimeOfDay = "01:00:00:"
wait(0)
game.Lighting.TimeOfDay = "02:00:00:"
wait(0)
game.Lighting.TimeOfDay = "03:00:00:"
wait(0)
game.Lighting.TimeOfDay = "04:00:00:"
wait(0)
game.Lighting.TimeOfDay = "05:00:00:"
wait(0)
game.Lighting.TimeOfDay = "06:00:00:"
wait(0)
game.Lighting.TimeOfDay = "07:00:00:"
wait(0)
game.Lighting.TimeOfDay = "08:00:00:"
wait(0)
game.Lighting.TimeOfDay = "09:00:00:"
wait(0)
game.Lighting.TimeOfDay = "10:00:00:"
wait(0)
game.Lighting.TimeOfDay = "11:00:00:"
wait(0)
game.Lighting.TimeOfDay = "12:00:00:"
wait(0)
game.Lighting.TimeOfDay = "13:00:00:"
wait(0)
game.Lighting.TimeOfDay = "14:00:00:"
wait(0)
game.Lighting.TimeOfDay = "15:00:00:"
wait(0)
game.Lighting.TimeOfDay = "16:00:00:"
wait(0)
game.Lighting.TimeOfDay = "17:00:00:"
wait(0)
game.Lighting.TimeOfDay = "18:00:00:"
wait(0)
game.Lighting.TimeOfDay = "19:00:00:"
wait(0)
game.Lighting.TimeOfDay = "20:00:00:"
wait(0)
game.Lighting.TimeOfDay = "21:00:00:"
wait(0)
game.Lighting.TimeOfDay = "22:00:00:"
wait(0)
game.Lighting.TimeOfDay = "23:00:00:"
wait(0)
game.Lighting.TimeOfDay = "24:00:00:"game.Lighting.TimeOfDay = "00:00:00:"
wait(0)
game.Lighting.TimeOfDay = "01:00:00:"
wait(0)
game.Lighting.TimeOfDay = "02:00:00:"
wait(0)
game.Lighting.TimeOfDay = "03:00:00:"
wait(0)
game.Lighting.TimeOfDay = "04:00:00:"
wait(0)
game.Lighting.TimeOfDay = "05:00:00:"
wait(0)
game.Lighting.TimeOfDay = "06:00:00:"
wait(0)
game.Lighting.TimeOfDay = "07:00:00:"
wait(0)
game.Lighting.TimeOfDay = "08:00:00:"
wait(0)
game.Lighting.TimeOfDay = "09:00:00:"
wait(0)
game.Lighting.TimeOfDay = "10:00:00:"
wait(0)
game.Lighting.TimeOfDay = "11:00:00:"
wait(0)
game.Lighting.TimeOfDay = "12:00:00:"
wait(0)
game.Lighting.TimeOfDay = "13:00:00:"
wait(0)
game.Lighting.TimeOfDay = "14:00:00:"
wait(0)
game.Lighting.TimeOfDay = "15:00:00:"
wait(0)
game.Lighting.TimeOfDay = "16:00:00:"
wait(0)
game.Lighting.TimeOfDay = "17:00:00:"
wait(0)
game.Lighting.TimeOfDay = "18:00:00:"
wait(0)
game.Lighting.TimeOfDay = "19:00:00:"
wait(0)
game.Lighting.TimeOfDay = "20:00:00:"
wait(0)
game.Lighting.TimeOfDay = "21:00:00:"
wait(0)
game.Lighting.TimeOfDay = "22:00:00:"
wait(0)
game.Lighting.TimeOfDay = "23:00:00:"
wait(0)
game.Lighting.TimeOfDay = "24:00:00:"game.Lighting.TimeOfDay = "00:00:00:"
wait(0)
game.Lighting.TimeOfDay = "01:00:00:"
wait(0)
game.Lighting.TimeOfDay = "02:00:00:"
wait(0)
game.Lighting.TimeOfDay = "03:00:00:"
wait(0)
game.Lighting.TimeOfDay = "04:00:00:"
wait(0)
game.Lighting.TimeOfDay = "05:00:00:"
wait(0)
game.Lighting.TimeOfDay = "06:00:00:"
wait(0)
game.Lighting.TimeOfDay = "07:00:00:"
wait(0)
game.Lighting.TimeOfDay = "08:00:00:"
wait(0)
game.Lighting.TimeOfDay = "09:00:00:"
wait(0)
game.Lighting.TimeOfDay = "10:00:00:"
wait(0)
game.Lighting.TimeOfDay = "11:00:00:"
wait(0)
game.Lighting.TimeOfDay = "12:00:00:"
wait(0)
game.Lighting.TimeOfDay = "13:00:00:"
wait(0)
game.Lighting.TimeOfDay = "14:00:00:"
wait(0)
game.Lighting.TimeOfDay = "15:00:00:"
wait(0)
game.Lighting.TimeOfDay = "16:00:00:"
wait(0)
game.Lighting.TimeOfDay = "17:00:00:"
wait(0)
game.Lighting.TimeOfDay = "18:00:00:"
wait(0)
game.Lighting.TimeOfDay = "19:00:00:"
wait(0)
game.Lighting.TimeOfDay = "20:00:00:"
wait(0)
game.Lighting.TimeOfDay = "21:00:00:"
wait(0)
game.Lighting.TimeOfDay = "22:00:00:"
wait(0)
game.Lighting.TimeOfDay = "23:00:00:"
wait(0)
game.Lighting.TimeOfDay = "24:00:00:"game.Lighting.TimeOfDay = "00:00:00:"
wait(0)
game.Lighting.TimeOfDay = "01:00:00:"
wait(0)
game.Lighting.TimeOfDay = "02:00:00:"
wait(0)
game.Lighting.TimeOfDay = "03:00:00:"
wait(0)
game.Lighting.TimeOfDay = "04:00:00:"
wait(0)
game.Lighting.TimeOfDay = "05:00:00:"
wait(0)
game.Lighting.TimeOfDay = "06:00:00:"
wait(0)
game.Lighting.TimeOfDay = "07:00:00:"
wait(0)
game.Lighting.TimeOfDay = "08:00:00:"
wait(0)
game.Lighting.TimeOfDay = "09:00:00:"
wait(0)
game.Lighting.TimeOfDay = "10:00:00:"
wait(0)
game.Lighting.TimeOfDay = "11:00:00:"
wait(0)
game.Lighting.TimeOfDay = "12:00:00:"
wait(0)
game.Lighting.TimeOfDay = "13:00:00:"
wait(0)
game.Lighting.TimeOfDay = "14:00:00:"
wait(0)
game.Lighting.TimeOfDay = "15:00:00:"
wait(0)
game.Lighting.TimeOfDay = "16:00:00:"
wait(0)
game.Lighting.TimeOfDay = "17:00:00:"
wait(0)
game.Lighting.TimeOfDay = "18:00:00:"
wait(0)
game.Lighting.TimeOfDay = "19:00:00:"
wait(0)
game.Lighting.TimeOfDay = "20:00:00:"
wait(0)
game.Lighting.TimeOfDay = "21:00:00:"
wait(0)
game.Lighting.TimeOfDay = "22:00:00:"
wait(0)
game.Lighting.TimeOfDay = "23:00:00:"
wait(0)
game.Lighting.TimeOfDay = "24:00:00:"game.Lighting.TimeOfDay = "00:00:00:"
wait(0)
game.Lighting.TimeOfDay = "01:00:00:"
wait(0)
game.Lighting.TimeOfDay = "02:00:00:"
wait(0)
game.Lighting.TimeOfDay = "03:00:00:"
wait(0)
game.Lighting.TimeOfDay = "04:00:00:"
wait(0)
game.Lighting.TimeOfDay = "05:00:00:"
wait(0)
game.Lighting.TimeOfDay = "06:00:00:"
wait(0)
game.Lighting.TimeOfDay = "07:00:00:"
wait(0)
game.Lighting.TimeOfDay = "08:00:00:"
wait(0)
game.Lighting.TimeOfDay = "09:00:00:"
wait(0)
game.Lighting.TimeOfDay = "10:00:00:"
wait(0)
game.Lighting.TimeOfDay = "11:00:00:"
wait(0)
game.Lighting.TimeOfDay = "12:00:00:"
wait(0)
game.Lighting.TimeOfDay = "13:00:00:"
wait(0)
game.Lighting.TimeOfDay = "14:00:00:"
wait(0)
game.Lighting.TimeOfDay = "15:00:00:"
wait(0)
game.Lighting.TimeOfDay = "16:00:00:"
wait(0)
game.Lighting.TimeOfDay = "17:00:00:"
wait(0)
game.Lighting.TimeOfDay = "18:00:00:"
wait(0)
game.Lighting.TimeOfDay = "19:00:00:"
wait(0)
game.Lighting.TimeOfDay = "20:00:00:"
wait(0)
game.Lighting.TimeOfDay = "21:00:00:"
wait(0)
game.Lighting.TimeOfDay = "22:00:00:"
wait(0)
game.Lighting.TimeOfDay = "23:00:00:"
wait(0)
game.Lighting.TimeOfDay = "24:00:00:"game.Lighting.TimeOfDay = "00:00:00:"
wait(0)
game.Lighting.TimeOfDay = "01:00:00:"
wait(0)
game.Lighting.TimeOfDay = "02:00:00:"
wait(0)
game.Lighting.TimeOfDay = "03:00:00:"
wait(0)
game.Lighting.TimeOfDay = "04:00:00:"
wait(0)
game.Lighting.TimeOfDay = "05:00:00:"
wait(0)
game.Lighting.TimeOfDay = "06:00:00:"
wait(0)
game.Lighting.TimeOfDay = "07:00:00:"
wait(0)
game.Lighting.TimeOfDay = "08:00:00:"
wait(0)
game.Lighting.TimeOfDay = "09:00:00:"
wait(0)
game.Lighting.TimeOfDay = "10:00:00:"
wait(0)
game.Lighting.TimeOfDay = "11:00:00:"
wait(0)
game.Lighting.TimeOfDay = "12:00:00:"
wait(0)
game.Lighting.TimeOfDay = "13:00:00:"
wait(0)
game.Lighting.TimeOfDay = "14:00:00:"
wait(0)
game.Lighting.TimeOfDay = "15:00:00:"
wait(0)
game.Lighting.TimeOfDay = "16:00:00:"
wait(0)
game.Lighting.TimeOfDay = "17:00:00:"
wait(0)
game.Lighting.TimeOfDay = "18:00:00:"
wait(0)
game.Lighting.TimeOfDay = "19:00:00:"
wait(0)
game.Lighting.TimeOfDay = "20:00:00:"
wait(0)
game.Lighting.TimeOfDay = "21:00:00:"
wait(0)
game.Lighting.TimeOfDay = "22:00:00:"
wait(0)
game.Lighting.TimeOfDay = "23:00:00:"
wait(0)
game.Lighting.TimeOfDay = "24:00:00:"game.Lighting.TimeOfDay = "00:00:00:"
wait(0)
game.Lighting.TimeOfDay = "01:00:00:"
wait(0)
game.Lighting.TimeOfDay = "02:00:00:"
wait(0)
game.Lighting.TimeOfDay = "03:00:00:"
wait(0)
game.Lighting.TimeOfDay = "04:00:00:"
wait(0)
game.Lighting.TimeOfDay = "05:00:00:"
wait(0)
game.Lighting.TimeOfDay = "06:00:00:"
wait(0)
game.Lighting.TimeOfDay = "07:00:00:"
wait(0)
game.Lighting.TimeOfDay = "08:00:00:"
wait(0)
game.Lighting.TimeOfDay = "09:00:00:"
wait(0)
game.Lighting.TimeOfDay = "10:00:00:"
wait(0)
game.Lighting.TimeOfDay = "11:00:00:"
wait(0)
game.Lighting.TimeOfDay = "12:00:00:"
wait(0)
game.Lighting.TimeOfDay = "13:00:00:"
wait(0)
game.Lighting.TimeOfDay = "14:00:00:"
wait(0)
game.Lighting.TimeOfDay = "15:00:00:"
wait(0)
game.Lighting.TimeOfDay = "16:00:00:"
wait(0)
game.Lighting.TimeOfDay = "17:00:00:"
wait(0)
game.Lighting.TimeOfDay = "18:00:00:"
wait(0)
game.Lighting.TimeOfDay = "19:00:00:"
wait(0)
game.Lighting.TimeOfDay = "20:00:00:"
wait(0)
game.Lighting.TimeOfDay = "21:00:00:"
wait(0)
game.Lighting.TimeOfDay = "22:00:00:"
wait(0)
game.Lighting.TimeOfDay = "23:00:00:"
wait(0)
game.Lighting.TimeOfDay = "24:00:00:"
game.Players.LocalPlayer.Character.Humanoid.Health = 0----set hp 
end
